Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -47,10 +47,11 @@ jobs:
           echo "Private key written to ~/.ssh/id_rsa"
           chmod 600 ~/.ssh/id_rsa
           echo "Permissions set for private key"
-          ssh-keyscan -H heroku.com >> ~/.ssh/known_hosts
+          ssh-keyscan -H heroku.com >> ~/.ssh/known_hosts || echo "ssh-keyscan failed"
           echo "Heroku.com added to known hosts"
         env:
           HEROKU_SSH_PRIVATE_KEY: ${{ secrets.HEROKU_SSH_PRIVATE_KEY }}
+
 
 
       - name: Set up Heroku Remote with SSH
