Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -43,10 +43,13 @@ jobs:
       - name: Setup SSH for Heroku
         run: |
           mkdir -p ~/.ssh/
+          echo "Directory created"
           echo "${{ secrets.HEROKU_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
+          echo "Private key written"
           chmod 600 ~/.ssh/id_rsa
-          ssh-keyscan -H heroku.com >> ~/.ssh/known_hosts
-          echo "Heroku.com added to known hosts"
+          echo "Permissions set"
+          ssh-keyscan -H heroku.com >> ~/.ssh/known_hosts && echo "Heroku.com added" || echo "ssh-keyscan failed"
+
         env:
           HEROKU_SSH_PRIVATE_KEY: ${{ secrets.HEROKU_SSH_PRIVATE_KEY }}
 
